# The objective is to perform VSTESTV2 with Diagnostics

trigger:
- master
jobs:
- job: RunTest4
  displayName: 'Run Tests'
  pool:
    vmImage: windows-latest
  steps:      
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'latestPreRelease'
  - task: VSTest@2
    inputs:  
      testSelector: 'testAssemblies'     
      testAssemblyVer2: '**/*StackOverflow*.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)\bin\Debug\'
      vsTestVersion: 'toolsInstaller'
      diagnosticsEnabled: true
