# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.

# Add steps that build, run tests, deploy, and more:

# https://aka.ms/yaml


trigger:

- master


jobs:
- job: RunTest4
  displayName: 'Run Tests'
  pool: Din_pool
  steps:      
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'latestPreRelease'
  - task: VSTest@2
    inputs:  
      testSelector: 'testAssemblies'     
      testAssemblyVer2: '**/*StackOverflow*.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)\bin\Debug\'
      vsTestVersion: 'toolsInstaller'
      diagnosticsEnabled: true
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'

        
